import math

def threshold(n):
    total = 2 ** n
    q1 = 0
    q2 = 0
    acc = 0
    for i in range(0, n+1):
        p = math.comb(n, i)
        if acc < 0.01 * total and acc + p >= 0.01 * total:
            q1 = i - 0.5
        if acc < 0.05 * total and acc + p >= 0.05 * total:
            q2 = i - 0.5
        acc += p
    if q1 < 0: q1 = 0
    if q2 < 0: q2 = 0
    return (q1/n, q2/n)

print("// generated by generate.py")
print("export const thresholds: [number, number, number, number][] = [");
print("  [0, 0, 1, 1],")
for i in range(1, 201):
    (x1, x2) = threshold(i)
    print(f"  [{x1}, {x2}, {1-x2}, {1-x1}],")
print("];\n")


def prob_at_least_one_run(n, k):
    probas = [0]

    keys = ["start", "final"] + ["p" + str(i) for i in range(1, k)] + ["f" + str(i) for i in range(1, k)]

    dp = dict((k, 0.0) for k in keys)
    dp["start"] = 1.0

    for step in range(1, n + 1):
        new_dp = dict((k, 0.0) for k in keys)
        new_dp["final"] = dp["final"]
        new_dp["p1"] += 0.5 * dp["start"]
        new_dp["f1"] += 0.5 * dp["start"] 
        for i in range(1, k):
            new_dp["f1"] += 0.5 * dp["p"+str(i)]
            new_dp["p1"] += 0.5 * dp["f"+str(i)]
            if i == k-1:
                new_dp["final"] += 0.5 * (dp["p"+str(i)] + dp["f"+str(i)])
            else:
                new_dp["p"+str(i+1)] += 0.5 * dp["p"+str(i)]
                new_dp["f"+str(i+1)] += 0.5 * dp["f"+str(i)]
        dp = new_dp
        probas.append(dp["final"])

    return probas

N = 200

probas = [prob_at_least_one_run(N, k) for k in range(2, 18)]

def pr(n, k):
    if k == 0:
        return 1
    elif n == 0:
        return 0
    elif k == 1:
        return 1
    else:
        return probas[k-2][n]

def run_thresholds(n):
    ro = 0
    ov = 0
    vo = 0
    or_ = 0
    for i in range(0, 17):
        if pr(n, i) > 0.99 and pr(n, i+1) <= 0.99:
            ro = max(0, i - 0.5)
        if pr(n, i) > 0.95 and pr(n, i+1) <= 0.95:
            ov = max(0, i - 0.5)
        if pr(n, i) >= 0.05 and pr(n, i+1) < 0.05:
            vo = min(i + 0.5, n)
        if pr(n, i) >= 0.01 and pr(n, i+1) < 0.01:
            or_ = min(i + 0.5, n)
            break
    return (ro, ov, vo, or_)

print("export const runThresholds: [number, number, number, number][] = [");
print("  [0, 0, 1, 1],")
print("  [0, 0, 1, 1],")
for i in range(2, 201):
    (x1, x2, x3, x4) = run_thresholds(i)
    print(f"  [{x1}, {x2}, {x3}, {x4}],")
print("]")